// This is some magic generated by the AI to make Prisma works with webpack
// when using a custom path for the generated client.
module.exports = function (options) {
  return {
    ...options,
    externals: [
      // Custom externals function that respects TypeScript paths
      function ({request}, callback) {
        // Don't externalize modules that have TypeScript path mappings
        const hasTsPath =
          request === "@prisma/client" ||
          request.startsWith("@app") ||
          request.startsWith("@services") ||
          request.startsWith("@domain") ||
          request.startsWith("@external") ||
          request.startsWith("@controllers") ||
          request.startsWith("@utils")

        if (hasTsPath) return callback()

        // Externalize other node_modules
        if (/^[^./]/.test(request)) return callback(null, "commonjs " + request)

        callback()
      }
    ]
  }
}
