/* eslint-disable @typescript-eslint/no-require-imports */
const path = require("path")

// This is some magic generated by the AI to make Prisma works with webpack
// when using a custom path for the generated client.
module.exports = function (options) {
  return {
    ...options,
    resolve: {
      ...options.resolve,
      alias: {
        ...options.resolve?.alias,
        "@app": path.resolve(__dirname, "app/main/src"),
        "@services": path.resolve(__dirname, "app/services/src"),
        "@domain": path.resolve(__dirname, "app/domain/src"),
        "@external": path.resolve(__dirname, "app/external/src"),
        "@controllers": path.resolve(__dirname, "app/controllers/src"),
        "@utils": path.resolve(__dirname, "app/utils/src"),
        "@test": path.resolve(__dirname, "app/test"),
        "@prisma/client": path.resolve(__dirname, "generated/prisma/client.ts")
      }
    },
    externals: [
      // Custom externals function that respects TypeScript paths
      function ({request}, callback) {
        // Don't externalize modules that have TypeScript path mappings
        const hasTsPath =
          request === "@prisma/client" ||
          request.startsWith("@app") ||
          request.startsWith("@services") ||
          request.startsWith("@domain") ||
          request.startsWith("@external") ||
          request.startsWith("@controllers") ||
          request.startsWith("@utils")

        if (hasTsPath) return callback()

        // Externalize other node_modules
        if (/^[^./]/.test(request)) return callback(null, "commonjs " + request)

        callback()
      }
    ]
  }
}
