import {SharedArray} from "k6/data"

export interface SeedUser {
  id: string
  token: string
}

export interface TemplateVoter {
  token: string
  groupId: string
}

export interface SeedTemplate {
  id: string
  name: string
  voters: TemplateVoter[]
}

export interface SeedData {
  users: SeedUser[]
  adminToken: string
  groups: string[]
  spaces: string[]
  templates: SeedTemplate[]
}

const seedData = new SharedArray<SeedData>("seed data", () => {
  // Read the seed data file generated by seed.ts
  // In k6, reading files must be done using the global JSON.parse and open() functions
  // within the init context.
  const f = JSON.parse(open("../seed-data.json")) as SeedData

  // Validate the data structure before returning
  if (!f || typeof f !== "object") throw new Error("Invalid seed data: root object is missing or invalid")
  if (!Array.isArray(f.users)) throw new Error("Invalid seed data: users is missing or not an array")
  if (typeof f.adminToken !== "string") throw new Error("Invalid seed data: adminToken is missing or not a string")
  if (!Array.isArray(f.groups)) throw new Error("Invalid seed data: groups is missing or not an array")
  if (!Array.isArray(f.spaces)) throw new Error("Invalid seed data: spaces is missing or not an array")
  if (!Array.isArray(f.templates)) throw new Error("Invalid seed data: templates is missing or not an array")

  return [f] // SharedArray requires an array return
})

export function getRandomUserToken(): string {
  const data = seedData[0]
  if (!data) throw new Error("Seed data is not initialized")
  if (!data.users || data.users.length === 0) throw new Error("No users found in seed data")

  const user = data.users[Math.floor(Math.random() * data.users.length)]
  if (!user) throw new Error("No user selected")
  return user.token
}

export function getAdminToken(): string {
  const data = seedData[0]
  if (!data) throw new Error("Seed data is not initialized")
  return data.adminToken
}

export function getRandomTemplate(): SeedTemplate {
  const data = seedData[0]
  if (!data) throw new Error("Seed data is not initialized")
  if (!data.templates || data.templates.length === 0) throw new Error("No templates found in seed data")

  const template = data.templates[Math.floor(Math.random() * data.templates.length)]
  if (!template) throw new Error("No template selected")
  return template
}

export function getRandomUser(): SeedUser {
  const data = seedData[0]
  if (!data) throw new Error("Seed data is not initialized")
  if (!data.users || data.users.length === 0) throw new Error("No users found in seed data")

  const user = data.users[Math.floor(Math.random() * data.users.length)]
  if (!user) throw new Error("No user selected")
  return user
}

export function getRandomVoterForTemplate(template: SeedTemplate): TemplateVoter {
  if (!template.voters || template.voters.length === 0) {
    throw new Error(`No voters found for template ${template.id}`)
  }
  const voter = template.voters[Math.floor(Math.random() * template.voters.length)]
  if (!voter) throw new Error("No voter selected")
  return voter
}
