import exec from "k6/execution"

// Helper to generate a unique string per VU and iteration
// Useful for creating unique names that don't violate DB constraints
export function generateUniqueName(prefix: string) {
  const vuId = exec.vu.idInTest
  const iter = exec.scenario.iterationInTest
  const ts = new Date().getTime()
  return `${prefix}-${vuId}-${iter}-${ts}`
}

export function generateWorkflowPayload(templateId: string) {
  return {
    name: generateUniqueName("load-wf"),
    description: "Generated by k6 load test",
    workflowTemplateId: templateId
  }
}

export function generateVotePayload(groupId: string) {
  return {
    voteType: {
      type: "APPROVE",
      votedForGroups: [groupId]
    }
  }
}
