@baseUrl = http://localhost:3000

# @name login
POST {{baseUrl}}/debug/login
Content-Type: application/json

{
  "email": "{{$guid}}@localhost.com"
}

###

@token = {{login.response.body.token}}

###

# @name createGroup
POST {{baseUrl}}/groups
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "{{$guid}}",
  "description": "Simple test group"
}

###

@groupLocation = {{createGroup.response.headers.Location}}

# @name getGroup
GET {{groupLocation}}
Content-Type: application/json
Authorization: Bearer {{token}} 